### ISSUE TITLE
Fulscreen Lion Bug

### ISSUE THREAD

**Issue by saibayadon** [maccman/macgap-rb#3]
[Pull #37](https://github.com/maccman/macgap/pull/37) Fixed this on the macgap repo, but i think that is missing from macgap-rb (Since happened with the demo app).

**Comment by nightofgrim** [comment]
![Screen Shot 2013-01-22 at 11 08 09 PM](https://f.cloud.github.com/assets/3349202/89239/31cd31dc-652c-11e2-81b6-b85043a1ddd5.png)

Is this "Fullscreen Lion Bug" the same I am experiencing in this screenshot? When going fullscreen the top does not draw or the webview does not reach the top of the screen.
